
CREATE TABLE if not exists `oneminute` (
  `tradingday` INT NOT NULL,
  `updatetime` INT NOT NULL,
  `instrumentid` text NOT NULL,
  `open` double NOT NULL,
  `high` double NOT NULL,
  `low` double NOT NULL,
  `close` double NOT NULL,
  `volume` int NOT NULL,
  `amount` int NOT NULL,
  `openint` int NOT NULL,
  PRIMARY KEY (`instrumentid`,`tradingday`,`updatetime`)
);

CREATE TABLE IF NOT EXISTS exchanges (
	id TEXT NOT NULL,
	name TEXT NOT NULL,
	date_start INT NOT NULL,
	date_last INT NOT NULL,
	manual_flag INT NOT NULL,
	update_time TEXT NOT NULL,
	PRIMARY KEY (id, name)
);

insert into `exchanges` values ('DQ','dce',19930301,date(),1,datetime());
insert into `exchanges` values ('SQ','shfe',20000101,date(),1,datetime());
insert into `exchanges` values ('ZQ','zce',19901101,date(),1,datetime());
insert into `exchanges` values ('ZJ','ceffex',20100416,date(),1,datetime());

CREATE TABLE if not exists sectors (
	id INT ,
	sector TEXT NOT NULL,
	name TEXT,
	min_date INT,
	max_date INT,
	exchange TEXT NOT NULL,
	manual_flag INT NOT NULL,	
	update_time INT NOT NULL,
	PRIMARY KEY (sector,exchange)
)		;

CREATE TABLE if not exists contracts (
	instrumentid TEXT NOT NULL,
	min_date INT,
	max_date INT,
	sector TEXT NOT NULL,
	manual_flag INT NOT NULL,	
	update_time INT NOT NULL,
	PRIMARY KEY (instrumentid)
)		;

CREATE TABLE IF NOT EXISTS tradingday (
	tradingday INT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS daily (
	tradingday INT NOT NULL,
	instrumentid TEXT NOT NULL,
	open DOUBLE NOT NULL,
	high DOUBLE NOT NULL,
	low DOUBLE NOT NULL,
	close DOUBLE NOT NULL,
	volume INT NOT NULL,
	openint INT NOT NULL,
	settlementprice DOUBLE NOT NULL,
    PreSettlementPrice DOUBLE NOT NULL,
    PreClosePrice DOUBLE NOT NULL,
    PreOpenInterest INT NOT NULL,
	PRIMARY KEY (tradingday, instrumentid)
);

CREATE TABLE IF NOT EXISTS quasi_daily (
	tradingday INT NOT NULL,
	updatetime INT NOT NULL,
	instrumentid TEXT NOT NULL,
	lowerlimitprice DOUBLE NOT NULL,
	upperlimitprice DOUBLE NOT NULL,
	PRIMARY KEY (tradingday, updatetime, instrumentid)
);


CREATE TABLE IF NOT EXISTS main_contracts (
	sector TEXT NOT NULL,
	instrumentid TEXT NOT NULL,
	tradingday INT NOT NULL,
	volume_or_openint INT NOT NULL,
	PRIMARY KEY (sector,instrumentid,tradingday,volume_or_openint)
);

CREATE TABLE IF NOT EXISTS mktvital (
	date INT NOT NULL,
	instrumentid TEXT NOT NULL,
	efficiency DOUBLE NOT NULL,
	volatility DOUBLE NOT NULL,
	hot DOUBLE NOT NULL,
	manual_flag INT NOT NULL,	
	update_time INT NOT NULL,
	PRIMARY KEY (date, instrumentid)
);

CREATE TABLE IF NOT EXISTS realizedcorr (
	date INT NOT NULL,
	instrumentid1 TEXT NOT NULL,
	instrumentid2 TEXT NOT NULL,
	corr DOUBLE NOT NULL,
	manual_flag INT NOT NULL,	
	update_time INT NOT NULL,
	PRIMARY KEY (date, instrumentid1, instrumentid2)	
);

CREATE TABLE IF NOT EXISTS continuous (
	instrumentid TEXT NOT NULL,
	date INT NOT NULL,
	PRIMARY KEY (date,instrumentid)
);

CREATE TABLE IF NOT EXISTS main (
	instrumentid TEXT UNIQUE NOT NULL
);

insert or ignore into main 
select distinct instrumentid from oneminute where substr(instrumentid,length(instrumentid)-1,2) == '00';



PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `tradingtime` (
tradingtime INT NOT NULL,
isjzttime INT NOT NULL,
PRIMARY KEY (tradingtime, isjzttime)
);

INSERT OR IGNORE INTO tradingtime 
select distinct cast(substr(updatetime,1,length(updatetime)-2) as integer) as dt, 1 from oneminute 
where instrumentid NOT in (
select distinct instrumentid from contracts where sector in (select distinct sector from sectors where exchange = "ZJ")
) 
and
dt >= 100 and dt <= 1900 order by dt ASC;

INSERT OR IGNORE INTO "tradingtime" VALUES(100,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(101,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(102,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(103,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(104,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(105,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(106,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(107,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(108,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(109,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(110,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(111,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(112,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(113,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(114,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(115,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(116,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(117,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(118,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(119,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(120,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(121,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(122,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(123,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(124,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(125,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(126,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(127,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(128,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(129,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(130,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(131,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(132,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(133,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(134,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(135,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(136,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(137,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(138,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(139,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(140,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(141,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(142,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(143,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(144,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(145,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(146,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(147,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(148,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(149,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(150,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(151,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(152,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(153,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(154,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(155,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(156,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(157,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(158,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(159,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(200,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(201,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(202,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(203,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(204,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(205,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(206,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(207,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(208,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(209,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(210,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(211,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(212,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(213,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(214,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(215,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(216,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(217,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(218,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(219,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(220,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(221,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(222,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(223,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(224,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(225,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(226,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(227,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(228,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(229,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(230,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(231,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(232,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(233,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(234,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(235,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(236,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(237,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(238,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(239,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(240,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(241,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(242,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(243,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(244,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(245,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(246,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(247,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(248,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(249,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(250,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(251,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(252,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(253,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(254,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(255,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(256,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(257,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(258,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(259,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(300,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(301,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(302,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(303,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(304,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(305,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(306,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(307,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(308,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(309,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(310,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(311,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(312,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(313,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(314,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(315,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(316,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(317,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(318,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(319,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(320,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(321,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(322,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(323,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(324,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(325,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(326,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(327,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(328,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(329,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(330,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(331,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(332,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(333,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(334,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(335,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(336,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(337,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(338,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(339,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(340,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(341,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(342,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(343,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(344,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(345,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(346,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(347,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(348,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(349,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(350,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(351,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(352,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(353,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(354,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(355,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(356,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(357,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(358,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(359,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(400,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(401,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(402,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(403,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(404,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(405,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(406,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(407,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(408,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(409,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(410,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(411,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(412,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(413,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(414,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(415,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(416,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(417,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(418,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(419,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(420,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(421,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(422,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(423,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(424,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(425,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(426,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(427,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(428,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(429,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(430,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(431,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(432,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(433,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(434,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(435,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(436,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(437,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(438,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(439,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(440,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(441,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(442,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(443,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(444,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(445,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(446,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(447,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(448,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(449,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(450,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(451,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(452,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(453,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(454,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(455,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(456,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(457,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(458,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(459,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(500,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(501,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(502,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(503,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(504,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(505,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(506,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(507,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(508,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(509,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(510,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(511,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(512,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(513,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(514,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(515,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(516,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(517,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(518,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(519,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(520,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(521,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(522,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(523,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(524,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(525,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(526,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(527,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(528,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(529,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(530,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(531,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(532,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(533,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(534,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(535,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(536,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(537,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(538,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(539,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(540,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(541,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(542,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(543,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(544,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(545,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(546,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(547,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(548,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(549,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(550,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(551,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(552,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(553,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(554,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(555,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(556,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(557,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(558,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(559,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(600,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(601,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(602,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(603,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(604,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(605,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(606,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(607,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(608,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(609,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(610,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(611,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(612,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(613,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(614,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(615,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(616,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(617,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(618,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(619,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(620,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(621,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(622,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(623,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(624,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(625,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(626,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(627,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(628,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(629,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(630,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1300,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1301,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1302,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1303,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1304,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1305,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1306,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1307,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1308,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1309,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1310,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1311,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1312,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1313,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1314,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1315,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1316,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1317,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1318,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1319,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1320,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1321,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1322,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1323,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1324,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1325,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1326,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1327,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1328,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1329,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1330,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1331,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1332,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1333,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1334,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1335,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1336,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1337,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1338,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1339,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1340,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1341,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1342,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1343,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1344,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1345,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1346,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1347,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1348,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1349,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1350,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1351,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1352,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1353,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1354,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1355,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1356,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1357,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1358,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1359,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1400,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1401,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1402,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1403,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1404,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1405,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1406,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1407,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1408,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1409,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1410,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1411,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1412,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1413,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1414,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1415,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1430,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1431,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1432,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1433,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1434,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1435,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1436,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1437,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1438,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1439,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1440,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1441,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1442,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1443,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1444,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1445,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1446,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1447,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1448,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1449,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1450,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1451,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1452,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1453,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1454,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1455,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1456,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1457,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1458,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1459,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1500,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1501,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1502,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1503,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1504,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1505,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1506,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1507,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1508,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1509,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1510,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1511,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1512,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1513,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1514,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1515,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1516,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1517,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1518,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1519,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1520,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1521,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1522,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1523,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1524,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1525,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1526,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1527,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1528,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1529,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1530,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1730,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1731,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1732,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1733,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1734,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1735,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1736,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1737,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1738,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1739,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1740,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1741,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1742,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1743,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1744,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1745,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1746,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1747,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1748,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1749,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1750,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1751,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1752,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1753,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1754,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1755,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1756,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1757,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1758,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1759,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1800,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1801,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1802,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1803,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1804,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1805,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1806,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1807,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1808,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1809,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1810,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1811,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1812,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1813,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1814,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1815,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1816,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1817,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1818,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1819,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1820,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1821,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1822,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1823,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1824,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1825,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1826,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1827,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1828,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1829,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1830,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1831,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1832,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1833,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1834,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1835,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1836,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1837,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1838,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1839,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1840,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1841,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1842,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1843,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1844,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1845,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1846,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1847,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1848,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1849,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1850,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1851,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1852,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1853,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1854,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1855,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1856,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1857,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1858,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1859,1);
INSERT OR IGNORE INTO "tradingtime" VALUES(1900,1);
COMMIT;
