par(mar = rep(2.3,4))
for (i in seq(pi/2, -4/3*pi, length = 12)) {
  plot(0,0,pch=20,ann=F,axes=F)
  arrows(0,0,cos(i),sin(i))
  axis(1,0,"6")
  axis(2,0,"9")
  axis(3,0,"12")
  axis(4,0,"3")
  box()
}

## http://cos.name 
############################################1###########################
# networkview(igraph)


# 散点图
with(iris,plot(Petal.Length,Petal.Width,col=rep(c("red","blue","green"),each=50),pch=rep(23:25,each=50)))
# 散点图 ggplot2 
require(ggplot2)
qplot(Petal.Length,Petal.Width,color=Species,shape=Species,data=iris)
# 散点matrix图
pairs(iris[,1:4],main="Anderson's iris data--3 species",pch=21,bg=c("red","green3","blue")[unclass(iris[["Species"]])])
# 散点sunflower
sunflowerplot(iris[,3:4])
# density --pie chart
pie.sales <- c(0.12,0.3,0.26,0.16,0.04,0.12)
names(pie.sales) <- c("A","B","C","D","E","F")
pie(pie.sales,col=c("purple","violetred1","green3","cornsilk","cyan","white"))
# density --hist gram
hist(rchisq(100,df=4),col="lightblue",border="pink",main="aa")
# density -- box line
boxplot(count~spray,data=InsectSprays,col="lightgray")
# density -- violin
require(vioplot)
uniform <- runif(2000,-4,4)
normal <- rnorm(2000,0,3)
vioplot(uniform,normal)
# density -- back to back hist gram
require(Hmisc)
age <- rnorm(1000,50,10)
sex <- sample(c("female",'male'),1000,TRUE)
out <- histbackback(split(age,sex))
barplot(-out[["left"]],col="red",horiz=TRUE,space=0,add=TRUE,axes=FALSE)
barplot(out[["right"]],col="blue",horiz=TRUE,space=0,add=TRUE,axes=FALSE)
# density -- beanplot

# scatter + density - vio
x <- rnorm(100)
y <- rnorm(100)
plot(x,y,xlim=c(-5,5),ylim=c(-5,5))
vioplot(x,col="tomato",horizontal=T,at=-4,add=T,lty=2,rectCol="gray")
vioplot(y,col="cyan",horizontal=F,at=-4,add=T,lty=2,rectCol="gray")
# 多元图 -- parrallel (MASS)
require(MASS)
parcoord(iris[,1:4],col=rep(2:4,each=50))
# 多元图 -- harmony curve (MSG)
require(MSG)
andrews_curve(iris[,1:4],col=rep(2:4,each=50))
# 多元图 -- spider network (climatol)
require(climatol)
data("windfr")
rosavent(windfr,4,4,ang=-3*pi/16,main="Annual windrose")
# 多元图 -- radar
palette(rainbow(12,s=0.6,v=0.75))
stars(t(windfr),len=0.8,key.loc=c(14,1.5),ncol=7,main="aa",draw.segments=T)
stars(t(iris[,1:4]),len=0.8,key.loc=c(14,1.5),ncol=7,main="aa",draw.segments=T)
# 多元图 -- 
stars(t(windfr))
stars(t(iris[,1:4]))
# 多元图 -- 
alpack::faces(t(windfr))
## geography --  idempotent
x <- 10*(1:nrow(volcano))
x.at <- seq(100,800,by=100)
y <- 10*(1:ncol(volcano))
y.at <- seq(100,600,by=100)
image(x,y,volcano,col=terrain.colors(100),axes=F)
contour(x,y,volcano,levels=seq(90,to=200,by=5),add=T,col="brown")
# 3d
x <- seq(-10,10,length=30)
y <- x
f <- function(x,y) {
  r <- sqrt(x^2+y^2)
  10*sin(r)/r
}
z <- outer(x,y,f)
z[is.na(z)] <- 1
persp(x,y,z,theta=30,phi=30,expand=0.5,col="lightblue")
# 3d -- demonstration
require(rgl)
x = y = seq(1,5,by=0.1)
m = outer(x,y,function(a,b) beta(a,b))
persp3d(x,y,m,col="green3",zlab="Beta(x,y")
# word-cloud
# corrplot www.d3coder.com
require(corrplot)
############################################animation###########################
require(animation)
## demos
knn.ani()
kmeans.ani()
buffon.needle()
## frames
ani.options()
saveSWF()
saveMovie()
saveHTML()
## genrating animation file
## 1) save pic generated by R as SWF
# save R code pic as SWF file
# SWFtools(www.swftools.org) needed
saveSWF()
# save as gif
# ImageMagick(www.imagemagick.org) needed
ani.options(convert="d:/tmp/convert.exe")
saveGIF({for (i in 1:10) plot(runif(10),ylim=0:1)})
# R2SWF
# save pic as SWF without other softwares.
# image2swf() PNG or JPG
# svg2swf() SVG(vector?)
# dev2swf() automatically pics generated by R
# swf2html() demonstrate SWF animation in html

# brownnian motion
require(R2SWF)
if (capabilities("cairo")) {
  olddir = setwd(tempdir())
  svg("Rplot%03d.svg", onefile=F)
  set.seed(123)
  x = rnorm(5)
  y = rnorm(5)
  for (i in 1:100) {
    plot(x<-x+0.1*rnorm(5),y<-y+0.1*rnorm(5),xlim=c(-3,3),ylim=c(-3,3),col="steelblue",pch=16,cex=2,xlab="x",ylab="y")
  }
  dev.off()  
  output = svg2swf(sprintf("Rplot%03d.svg",1:100),interval=0.1)
  swf2html(output)
  setwd(olddir)
}
# http://wenku.it168.com/d_001393485.shtml 

## kmeans clustering
require(animation)
output <- dev2swf({par(mar=c(3,3,1,1.5),mgp=(1.5,0.5,0)),kmeans.ani()},output="test.swf")
swf2html(output)

## animation in a webpage
# flash
# gif
# js: http://taiyun.github.com/

## fractal trees
drawTree <- function(x1,y1,angle,n,lwd,len,col) {
  if (n>=1) {
    x2 <- x1+cos(angle)*len[n]*10
    y2 <- y1+sin(angle)*len[n]*10
    lines(c(x1,x2),c(y1,y2),lwd=lwd[n],col=col[n])
    drawTree(x2,y2,angle-pi/9,n-1,lwd,len,col)
    drawTree(x2,y2,angle+pi/9,n-1,lwd,len,col)
  }
}
COL <- rev(terrain.colors(16)[1:9])  
windows(width=6,height=4)
par(mar=c(0,0,0,0),ask=TRUE)
for (i in 1:9) {
  plot(0,xlim=c(-260,260),ylim=c(0,450),type="n",axes=F)
  drawTree(0,0,angle=pi/2,n=i,lwd=(10-i):9,len=(10-i):9,col=COL[(10-i):9])
}

  

